<?php

require_once '../classes/Item.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-11 at 16:20:36.
 */
class ItemTest extends PHPUnit_Framework_TestCase {

    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * 
     * @param Item $item
     * @param real $expectedTax
     * 
     * @dataProvider providerTestReturnsCorrectTax
     */
    public function testReturnsCorrectTax(Item $item, $expectedTax) {
        $item = new Item('item', 12.49, 0.0, 0.0);
        
        $expectedTax = 0.0;
        
        $actualTax = $item->getTotalTax();
        
        $this->assertEquals($expectedTax, $actualTax);
    }
    
    function providerTestReturnsCorrectTax() {
        $basicTaxRate = 0.1;
        $importDutyRate = 0.05;
        $noTaxRate = 0.0;
        
        return [
            [new Item('book', 12.49, $noTaxRate, $noTaxRate), 0.0],
            [new Item('music CD', 14.99, $basicTaxRate, $noTaxRate), 16.49],
            [new Item('imported bottle of perfume', 47.50, $basicTaxRate, $importDutyRate), 54.65],
            [new Item('imported box of chocolates', 11.25, $noTaxRate, $importDutyRate), 11.85],
        ];
    }

}
